name: regression
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  regression-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test
        uses: actions/checkout@v7
      - name: java setup
        uses: actions/setup-java@v6
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '25'
      - name: Run Tests
        run: mvn test -DsuiteXmlFile=regression-parallel.xml
        continue-on-error: true
      - name: Upload Report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: regression-report
          path: "**/*.html"



